%% Generated by the Erlang ASN.1 compiler. Version: 5.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module IPMSAutoActionTypes.

-ifndef(_IPMSAUTOACTIONTYPES_HRL_).
-define(_IPMSAUTOACTIONTYPES_HRL_, true).

-record('IPMAutoForwardRegistrationParameter', {
  filter = asn1_NOVALUE,
  'forwarding-envelope',
  'forwarding-heading',
  'forwarding-cover-note' = asn1_NOVALUE,
  'submission-options' = asn1_NOVALUE,
  'nrn-comment' = asn1_NOVALUE,
  'ipm-auto-forward-options' = asn1_DEFAULT
}).

-record('AutoForwardRegistrationParameter88', {
  filter = asn1_NOVALUE,
  'auto-forward-arguments',
  'delete-after-auto-forwarding' = asn1_DEFAULT,
  'forwarding-information'
}).

-record('AutoForwardArguments', {
  'originator-name',
  'content-identifier' = asn1_NOVALUE,
  priority = asn1_NOVALUE,
  'per-message-indicators' = asn1_NOVALUE,
  'deferred-delivery-time' = asn1_NOVALUE,
  extensions = asn1_DEFAULT,
  'per-recipient-fields'
}).

-record('AutoForwardArguments_extensions_SETOF', {
  type,
  criticality = asn1_DEFAULT,
  value = asn1_DEFAULT
}).

-record('PerMessageAutoForwardFields', {
  'originator-name',
  'content-identifier' = asn1_NOVALUE,
  priority = asn1_NOVALUE,
  'per-message-indicators' = asn1_NOVALUE,
  'deferred-delivery-time' = asn1_NOVALUE,
  extensions = asn1_DEFAULT
}).

-record('PerMessageAutoForwardFields_extensions_SETOF', {
  type,
  criticality = asn1_DEFAULT,
  value = asn1_DEFAULT
}).

-record('PerRecipientAutoForwardFields', {
  'recipient-name',
  'originator-report-request',
  'explicit-conversion' = asn1_NOVALUE,
  extensions = asn1_DEFAULT
}).

-record('PerRecipientAutoForwardFields_extensions_SETOF', {
  type,
  criticality = asn1_DEFAULT,
  value = asn1_DEFAULT
}).

-record('ForwardingInformation1988', {
  'auto-forwarding-comment' = asn1_NOVALUE,
  'ia5-cover-note' = asn1_NOVALUE,
  'this-ipm-prefix' = asn1_NOVALUE
}).

-record('IPMAutoAcknowledgementRegistrationParameter', {
  'auto-acknowledge-suppl-receipt-info' = asn1_NOVALUE,
  'submission-options' = asn1_NOVALUE
}).

-record('IPMAutoDiscardRegistrationParameter', {
  filter = asn1_NOVALUE,
  'submission-options' = asn1_NOVALUE,
  'auto-discard-expired-ipms',
  'auto-discard-obsoleted-ipms',
  'restrict-obsoleting-to-originator'
}).

-record('IPMAutoAdviseRegistrationParameter', {
  enabled = asn1_DEFAULT,
  filter = asn1_NOVALUE,
  'advice-notifications',
  'suppress-subsequent-notifications' = asn1_DEFAULT,
  'use-ipm-if-an-not-supported' = asn1_DEFAULT,
  'submission-options' = asn1_NOVALUE
}).

-record('IPMAutoAdviseRegistrationParameter_advice-notifications_SETOF', {
  type,
  value = asn1_DEFAULT
}).

-record('EXTERNAL', {
  'direct-reference' = asn1_NOVALUE,
  'indirect-reference' = asn1_NOVALUE,
  'data-value-descriptor' = asn1_NOVALUE,
  encoding
}).

-endif. %% _IPMSAUTOACTIONTYPES_HRL_
