%% Generated by the Erlang ASN.1 compiler. Version: 5.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module IPMSFileTransferBodyPartType.

-ifndef(_IPMSFILETRANSFERBODYPARTTYPE_HRL_).
-define(_IPMSFILETRANSFERBODYPARTTYPE_HRL_, true).

-record('FileTransferParameters', {
  'related-stored-file' = asn1_NOVALUE,
  'contents-type' = asn1_DEFAULT,
  environment = asn1_NOVALUE,
  compression = asn1_NOVALUE,
  'file-attributes' = asn1_NOVALUE,
  extensions = asn1_NOVALUE
}).

-record('RelatedStoredFile_SETOF', {
  'file-identifier',
  relationship = asn1_DEFAULT
}).

-record('PathnameandVersion', {
  pathname,
  'file-version' = asn1_NOVALUE
}).

-record('CrossReference', {
  'application-cross-reference',
  'message-reference' = asn1_NOVALUE,
  'body-part-reference' = asn1_NOVALUE
}).

-record('MessageReference', {
  user = asn1_NOVALUE,
  'user-relative-identifier'
}).

-record('Contents-Type-Attribute_document-type', {
  'document-type-name',
  parameter = asn1_NOVALUE
}).

-record('Contents-Type-Attribute_constraint-set-and-abstract-syntax', {
  'constraint-set-name',
  'abstract-syntax-name'
}).

-record('EnvironmentParameter', {
  'application-reference' = asn1_NOVALUE,
  machine = asn1_NOVALUE,
  'operating-system' = asn1_NOVALUE,
  'user-visible-string' = asn1_NOVALUE
}).

-record('CompressionParameter', {
  'compression-algorithm-id',
  'compression-algorithm-param'
}).

-record('FileAttributes', {
  pathname = asn1_NOVALUE,
  'permitted-actions' = asn1_NOVALUE,
  'storage-account' = asn1_NOVALUE,
  'date-and-time-of-creation' = asn1_NOVALUE,
  'date-and-time-of-last-modification' = asn1_NOVALUE,
  'date-and-time-of-last-read-access' = asn1_NOVALUE,
  'date-and-time-of-last-attribute-modification' = asn1_NOVALUE,
  'identity-of-creator' = asn1_NOVALUE,
  'identity-of-last-modifier' = asn1_NOVALUE,
  'identity-of-last-reader' = asn1_NOVALUE,
  'identity-of-last-attribute-modifier' = asn1_NOVALUE,
  'object-availability' = asn1_NOVALUE,
  'object-size' = asn1_NOVALUE,
  'future-object-size' = asn1_NOVALUE,
  'access-control' = asn1_NOVALUE,
  'legal-qualifications' = asn1_NOVALUE,
  'private-use' = asn1_NOVALUE,
  'attribute-extensions' = asn1_NOVALUE
}).

-record('Access-Control-Element', {
  'action-list',
  'concurrency-access' = asn1_NOVALUE,
  identity = asn1_NOVALUE,
  passwords = asn1_NOVALUE,
  location = asn1_NOVALUE
}).

-record('Access-Passwords', {
  'read-password',
  'insert-password',
  'replace-password',
  'extend-password',
  'erase-password',
  'read-attribute-password',
  'change-attribute-password',
  'delete-password',
  'pass-passwords',
  'link-password'
}).

-record('Application-Entity-Title', {
  'ap-title',
  'ae-qualifier'
}).

-record('EXTERNAL', {
  'direct-reference' = asn1_NOVALUE,
  'indirect-reference' = asn1_NOVALUE,
  'data-value-descriptor' = asn1_NOVALUE,
  encoding
}).

-endif. %% _IPMSFILETRANSFERBODYPARTTYPE_HRL_
