%% Generated by the Erlang ASN.1 compiler. Version: 5.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module IPMSHeadingExtensions.

-ifndef(_IPMSHEADINGEXTENSIONS_HRL_).
-define(_IPMSHEADINGEXTENSIONS_HRL_, true).

-record('BodyPartSignatures_SETOF', {
  'body-part-number',
  'body-part-signature',
  'originator-certificate-selector' = asn1_NOVALUE,
  'originator-certificates' = asn1_NOVALUE
  %% with extension mark
}).

-record('BodyPartSignature', {
  algorithmIdentifier,
  encrypted
}).

-record('IPMSecurityLabel', {
  'content-security-label',
  'heading-security-label' = asn1_NOVALUE,
  'body-part-security-labels' = asn1_NOVALUE
}).

-record('CirculationMember', {
  'circulation-recipient',
  checked = asn1_NOVALUE
}).

-record('CirculationSignature', {
  toBeSigned,
  algorithmIdentifier,
  encrypted
}).

-record('CirculationSignature_toBeSigned', {
  'algorithm-identifier',
  'this-IPM',
  timestamp
}).

-record('DistributionCode', {
  'oid-code' = asn1_NOVALUE,
  'alphanumeric-code' = asn1_NOVALUE,
  'or-descriptor' = asn1_NOVALUE
}).

-record('InformationCategory', {
  reference = asn1_NOVALUE,
  description = asn1_NOVALUE
}).

-endif. %% _IPMSHEADINGEXTENSIONS_HRL_
