-define(MAIN_CH, games_ch).
-define(USR_CHUNK, [feed, direct, sent, archive, products, starred, pinned, comments, cart, wishlist]).
-define(GRP_CHUNK, [feed, products, comments]).
-define(PRD_CHUNK, [features, specs, gallery, videos, reviews, news, bundles, comments]).
