%% Generated by the Erlang ASN.1 compiler. Version: 5.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module IPMSInformationObjects.

-ifndef(_IPMSINFORMATIONOBJECTS_HRL_).
-define(_IPMSINFORMATIONOBJECTS_HRL_, true).

-record('IPMSExtension', {
  type,
  value = asn1_DEFAULT
}).

-record('ExtendedBodyPart', {
  parameters = asn1_NOVALUE,
  data
}).

-record('IPM', {
  heading,
  body
}).

-record('Heading', {
  'this-IPM',
  originator = asn1_NOVALUE,
  'authorizing-users' = asn1_NOVALUE,
  'primary-recipients' = asn1_DEFAULT,
  'copy-recipients' = asn1_DEFAULT,
  'blind-copy-recipients' = asn1_NOVALUE,
  'replied-to-IPM' = asn1_NOVALUE,
  'obsoleted-IPMs' = asn1_DEFAULT,
  'related-IPMs' = asn1_DEFAULT,
  subject = asn1_NOVALUE,
  'expiry-time' = asn1_NOVALUE,
  'reply-time' = asn1_NOVALUE,
  'reply-recipients' = asn1_NOVALUE,
  importance = asn1_DEFAULT,
  sensitivity = asn1_NOVALUE,
  'auto-forwarded' = asn1_DEFAULT,
  extensions = asn1_DEFAULT
}).

-record('IPMIdentifier', {
  user = asn1_NOVALUE,
  'user-relative-identifier'
}).

-record('RecipientSpecifier', {
  recipient,
  'notification-requests' = asn1_DEFAULT,
  'reply-requested' = asn1_DEFAULT,
  'recipient-extensions' = asn1_NOVALUE
}).

-record('ORDescriptor', {
  'formal-name' = asn1_NOVALUE,
  'free-form-name' = asn1_NOVALUE,
  'telephone-number' = asn1_NOVALUE
}).

-record('RecipientExtensionsField_SETOF', {
  type,
  value = asn1_DEFAULT
}).

-record('ExtensionsField_SETOF', {
  type,
  value = asn1_DEFAULT
}).

-record('BodyPart_extended', {
  parameters = asn1_NOVALUE,
  data
}).

-record('IA5TextBodyPart', {
  parameters,
  data
}).

-record('IA5TextParameters', {
  repertoire = asn1_DEFAULT
}).

-record('G3FacsimileBodyPart', {
  parameters,
  data
}).

-record('G3FacsimileParameters', {
  'number-of-pages' = asn1_NOVALUE,
  'non-basic-parameters' = asn1_NOVALUE
}).

-record('TeletexBodyPart', {
  parameters,
  data
}).

-record('TeletexParameters', {
  'number-of-pages' = asn1_NOVALUE,
  'telex-compatible' = asn1_DEFAULT,
  'non-basic-parameters' = asn1_NOVALUE
}).

-record('VideotexBodyPart', {
  parameters,
  data
}).

-record('VideotexParameters', {
  syntax = asn1_NOVALUE
}).

-record('EncryptedBodyPart', {
  parameters,
  data
}).

-record('EncryptedParameters', {
  'algorithm-identifier',
  'originator-certificates' = asn1_NOVALUE
  %% with extension mark
}).

-record('MessageBodyPart', {
  parameters,
  data
}).

-record('MessageParameters', {
  'delivery-time' = asn1_NOVALUE,
  'delivery-envelope' = asn1_NOVALUE
}).

-record('IPN', {
  'subject-ipm',
  'ipn-originator' = asn1_NOVALUE,
  'ipm-intended-recipient' = asn1_NOVALUE,
  'conversion-eits' = asn1_NOVALUE,
  'notification-extensions' = asn1_NOVALUE,
  choice
}).

-record('CommonFields', {
  'subject-ipm',
  'ipn-originator' = asn1_NOVALUE,
  'ipm-intended-recipient' = asn1_NOVALUE,
  'conversion-eits' = asn1_NOVALUE,
  'notification-extensions' = asn1_NOVALUE
}).

-record('NonReceiptFields', {
  'non-receipt-reason',
  'discard-reason' = asn1_NOVALUE,
  'auto-forward-comment' = asn1_NOVALUE,
  'returned-ipm' = asn1_NOVALUE,
  'nrn-extensions' = asn1_NOVALUE
}).

-record('ReceiptFields', {
  'receipt-time',
  'acknowledgment-mode' = asn1_DEFAULT,
  'suppl-receipt-info' = asn1_NOVALUE,
  'rn-extensions' = asn1_NOVALUE
}).

-record('NotificationExtensionsField_SETOF', {
  type,
  value = asn1_DEFAULT
}).

-record('NRNExtensionsField_SETOF', {
  type,
  value = asn1_DEFAULT
}).

-record('RNExtensionsField_SETOF', {
  type,
  value = asn1_DEFAULT
}).

-record('OtherNotificationTypeFields_SETOF', {
  type,
  value = asn1_DEFAULT
}).

-record('AbsenceAdvice', {
  advice = asn1_NOVALUE,
  'next-available' = asn1_NOVALUE
}).

-record('ChangeOfAddressAdvice', {
  'new-address',
  'effective-from' = asn1_NOVALUE
}).

-record('IPMAssemblyInstructions', {
  'assembly-instructions'
}).

-record('BodyPartReference_stored-body-part', {
  'message-entry',
  'body-part-number'
}).

-record('EXTERNAL', {
  'direct-reference' = asn1_NOVALUE,
  'indirect-reference' = asn1_NOVALUE,
  'data-value-descriptor' = asn1_NOVALUE,
  encoding
}).

-record('INSTANCE OF', {
  'type-id',
  value
}).

-endif. %% _IPMSINFORMATIONOBJECTS_HRL_
